-- nuke.sql

DROP TABLE IF EXISTS seats_reservations CASCADE;
DROP TABLE IF EXISTS event_seats CASCADE;
DROP TABLE IF EXISTS event_section_prices CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS sections CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS users CASCADE;

